### ISSUE TITLE
Controle de versão?

### ISSUE THREAD

**Issue by afonsopacifer** [busca-dev/busca-starter-kit#2]
Como iremos manter o controle das versões do projeto?

> exemplo: 1.0.0 , 1.1.0, etc...

Usaremos as tags e releases do github para controlar isso.
Mas sobre a metodologia adotada para manter a organização, como faremos?
Eu sugiro seguir a [Semantic Versioning](http://semver.org/).

@busca-dev/owners

**Comment by CLAUDIOSERPA** [comment]
Afonso.

Define e me passa.

Obrigado.

**Comment by afonsopacifer** [comment]
OK, seguiremos então o [Semantic Versioning](http://semver.org/).
Sugiro que todos deem uma lida em como funciona,
o documento para leitura é pequeno, da para ler em 2 min.

**Comment by CLAUDIOSERPA** [comment]
Afonso,

Li o documento.

Isso mesmo que estou acostumado e a ver no mercado. Bom padrão.

Escreve um mini guia para o pessoal seguir com o guideline base.

Vamos melhorando pouco a pouco.

Obrigado.

Abraços,

Claudio Serpa

**Comment by afonsopacifer** [comment]
OK,
O Semantic Versioning tem documentação em pt-br,
[Semantic Versioning em pt-br](http://semver.org/lang/pt-BR/)
vou adicionar o este link ao  readme do projeto
