### ISSUE TITLE
Escolha da licença

### ISSUE THREAD

**Issue by afonsopacifer** [busca-dev/busca-starter-kit#3]
Como o projeto está aberto, qualquer um pode contribuir ou usar o projeto, o que é muito bom!

Porém precisamos manter uma licença, para preservarmos os nossos direitos, etc..

Para escolher a melhor licença temos o site [escolhaumalicenca](http://escolhaumalicenca.com.br/).

Eu sugiro a licença MIT como [nesse exemplo](https://github.com/afonsopacifer/flex-grid-framework/blob/master/licence.md)

@busca-dev/owners

**Comment by CLAUDIOSERPA** [comment]
Ok.

Pode usar.

Abracos.
